// Portfolio Content Data
// Generated by Portfolio Editor — 7/28/2026
// Save this file as js/data.js in your portfolio folder.
//
// Images and the CV live as real files under assets/ — this file only holds
// their paths, so the browser can fetch them in parallel and cache them.
//
// Live preview: if an unsaved draft exists in this browser (created by the
// editor), it takes priority so index.html reflects edits immediately.
// Visitors have no draft, so they always see the published content below.

(function () {
  var FILE_DATA = {
  "meta": {
    "name": "Victor Qixun Wu",
    "siteTitle": "Victor Qixun Wu — Colorist & Editor"
  },
  "hero": {
    "label": "Colorist · Vancouver, BC",
    "line1": "victor wu",
    "line2": "Victor Qixun Wu",
    "description": "Imaging and color specialist with 7+ years of post-production experience across color grading, digital imaging pipelines, and on-set media workflows — 60+ delivered projects spanning narrative film, VFX-adjacent productions, and branded campaigns.",
    "reelUrl": "https://vimeo.com/1084473056?share=copy&fl=cl&fe=ci"
  },
  "about": {
    "photo": "assets/portrait.jpg",
    "bio": [
      "<strong>Victor Qixun Wu</strong> is an imaging and color specialist with 7+ years of post-production experience across color grading, digital imaging pipelines, and on-set media workflows. Expert in DaVinci Resolve across Rec.709, Log, and HDR color pipelines including full DCP delivery for cinema.",
      "Deep hands-on experience in the complete imaging workflow: media ingestion, secure offload, QC, metadata organization, color space management, and multi-format delivery. Background as on-set DIT bridges creative and technical environments — detail-oriented, collaborative, and built for world-class post production pipelines."
    ],
    "skills": [
      {
        "category": "Color Grading",
        "items": [
          "DaVinci Resolve",
          "Premiere Pro",
          "Rec.709 / Log / HDR",
          "DCP Delivery",
          "Project Management",
          "Project Coordination ",
          "Cross-Platform QC"
        ]
      },
      {
        "category": "Camera & On-Set",
        "items": [
          "ARRI / Sony / Canon / Blackmagic",
          "Camera Operation",
          "Focus Pulling",
          "DIT",
          "Media Ingestion & Offload"
        ]
      },
      {
        "category": "Formats & Codecs",
        "items": [
          "ProRes, DNxHD, H.264/H.265",
          "RAW Formats",
          "DCP",
          "Digital Cinema Resolutions",
          "Multi-Format Export & Compliance"
        ]
      },
      {
        "category": "Post & Tools",
        "items": [
          "After Effects",
          "Photoshop",
          "Shotput Pro",
          "Frame.io",
          "Multicam Editing"
        ]
      }
    ],
    "cvLabel": "Download CV",
    "cvFileName": "Victor_Wu_CV.pdf",
    "cvUrl": "assets/doc/victor-wu-cv.pdf"
  },
  "portfolio": [
    {
      "id": "film",
      "name": "Film",
      "works": [
        {
          "id": "film-1",
          "title": "Crocs of the Caribbean",
          "year": "2026",
          "role": "Colorist",
          "description": "Color grading for a National Geographic documentary production. Currently in post-production.",
          "tags": [
            "National Geographic",
            "Documentary"
          ],
          "coverImage": "assets/works/film-crocs-of-the-caribbean.jpg",
          "links": {
            "live": "",
            "case_study": "https://www.rotatingplanet.com/project/crocs-of-the-caribbean"
          }
        },
        {
          "id": "film-2",
          "title": "We’re More than Sunsets",
          "year": "2026",
          "role": "Colorist",
          "description": "Feature-length film. Executed complete color pipeline — from dailies review through DCP final delivery — with full post supervision and director collaboration. Managed color space conversions, display calibration, and delivery specifications throughout.",
          "tags": [
            "Feature Film",
            "DCP",
            "Festival"
          ],
          "coverImage": "assets/works/film-we-re-more-than-sunsets.jpg",
          "links": {
            "live": "",
            "case_study": "https://www.themoviedb.org/movie/1621846-y-a-pas-juste-la-mer"
          }
        },
        {
          "id": "film-3",
          "title": "Anastasia",
          "year": "2024",
          "role": "Executive Producer, 1st AC  & Colorist",
          "description": "Official Selection, CINELEBU – Lebu International Film Festival 2025 (Oscar & Goya qualifying). Led full color post pipeline from pre-production through final DCP delivery; oversaw imaging and color consistency across all deliverables.",
          "tags": [
            "Short Film",
            "DCP",
            "Oscar Qualifying",
            "Festival"
          ],
          "coverImage": "assets/works/film-anastasia.jpg",
          "links": {
            "live": "",
            "case_study": "https://www.imdb.com/title/tt27598145/"
          }
        },
        {
          "id": "film-1785181922734",
          "title": "Avec le vent et les feuilles",
          "year": "2026",
          "role": "Colorist",
          "description": "Served as colorist on Avec le vent et les feuilles (2026), a short documentary following an elderly woman living atop a hill, surrounded by her passions, memories, and solitude. Applied a sepia film emulation grade to evoke nostalgia and the passage of time.",
          "tags": [
            "Short",
            "Documentary",
            "DCP"
          ],
          "coverImage": "assets/works/film-avec-le-vent-et-les-feuilles.jpg",
          "links": {
            "live": "",
            "case_study": "https://www.imdb.com/title/tt39126986/"
          }
        },
        {
          "id": "film-1785181057530",
          "title": "Ouija: La voix silencieuse",
          "year": "2025",
          "role": "Colorist",
          "description": "Served as colorist on Ouija: La voix silencieuse, a horror short following six girls whose Ouija board session unleashes a malevolent spirit at an isolated winter camp. Crafted a cold, foreboding grade to heighten the film's tension and supernatural dread.",
          "tags": [
            "Short Film",
            "Festival"
          ],
          "coverImage": "assets/works/film-ouija-la-voix-silencieuse.jpg",
          "links": {
            "live": "",
            "case_study": "https://www.imdb.com/title/tt36576706/?ref_=nm_flmg_job_3_accord_2_cdt_t_3"
          }
        },
        {
          "id": "film-1785181524332",
          "title": "Halloween Stalks II",
          "year": "2024",
          "role": "Colorist",
          "description": "Served as colorist on Halloween Stalks II, a horror short in which a mysterious figure comes knocking on Halloween night. Built a dark, high-contrast grade to amplify the film's dread and keep the supernatural threat lurking in the shadows.",
          "tags": [
            "Short Film",
            "Festival"
          ],
          "coverImage": "assets/works/film-halloween-stalks-ii.jpg",
          "links": {
            "live": "",
            "case_study": "https://www.imdb.com/title/tt30782276/?ref_=nm_flmg_job_3_accord_2_cdt_t_7"
          }
        },
        {
          "id": "film-1785178888690",
          "title": "Untold Valor",
          "year": "2026",
          "role": "Colorist",
          "description": "Served as colorist on Untold Valor, a war drama exploring themes of sacrifice and courage. Developed a gritty, immersive grade to support the film's emotional weight and combat authenticity.",
          "tags": [
            "Short Film"
          ],
          "coverImage": "assets/works/film-untold-valor.jpg",
          "links": {
            "live": "",
            "case_study": "https://www.imdb.com/title/tt31065576/?ref_=nm_flmg_job_1_accord_2_cdt_c_1"
          }
        },
        {
          "id": "film-1785224727258",
          "title": "Foosball Fever",
          "year": "2024",
          "role": "Colorist",
          "description": "Served as colorist on Foosball Fever (2024), a short film shot in black and white using an infrared camera and Red Komodo. Developed a grade that preserved the distinctive infrared texture and tonal contrast inherent to the camera combination.",
          "tags": [
            "Short",
            "Experimental"
          ],
          "coverImage": "assets/works/film-foosball-fever.jpg",
          "links": {
            "live": "",
            "case_study": ""
          }
        },
        {
          "id": "film-1785178471540",
          "title": "Frank and Edna Take on Le Mans",
          "year": "2026",
          "role": "Colorist",
          "description": "Served as colorist on Frank and Edna Take on Le Mans, a comedy short following an elderly man's absurdist bid to race at Le Mans after a terminal diagnosis — balancing warmth and dark humor through a grounded, character-driven grade.",
          "tags": [
            "Short Film"
          ],
          "coverImage": "assets/works/film-frank-and-edna-take-on-le-mans.jpg",
          "links": {
            "live": "",
            "case_study": "https://www.imdb.com/title/tt14818650/?ref_=nm_knf_t_4"
          }
        },
        {
          "id": "film-1785181677580",
          "title": "The Morning After",
          "year": "2024",
          "role": "Colorist",
          "description": "Served as colorist on The Morning After (2024), a comedy short. Developed a bright, punchy grade to complement the film's sharp comedic tone.",
          "tags": [
            "Short Film"
          ],
          "coverImage": "assets/works/film-the-morning-after.jpg",
          "links": {
            "live": "",
            "case_study": "https://www.imdb.com/title/tt32283477/?ref_=mv_close"
          }
        }
      ]
    },
    {
      "id": "commercial",
      "name": "Commercial",
      "works": [
        {
          "id": "comm-1",
          "title": "Prada Story Special",
          "year": "2024",
          "role": "Editor & Colorist",
          "description": "High-fashion branded content for Prada. Delivered multi-platform asset suite including social cuts and web masters, maintaining brand-consistent color language and image integrity across all outputs.",
          "tags": [
            "Fashion",
            "Brand",
            "Luxury"
          ],
          "coverImage": "assets/works/commercial-prada-story-special.jpg",
          "links": {
            "live": "",
            "case_study": ""
          }
        },
        {
          "id": "comm-2",
          "title": "ADERERROR 25FW ‘THE FUTURE IS NOT SET’",
          "year": "2025",
          "role": "Colorist",
          "description": "Fashion advertising campaign for the Seoul-based avant-garde label. Delivered a distinct, edgy visual aesthetic with precise color control across multi-platform outputs.",
          "tags": [
            "Fashion",
            "Brand"
          ],
          "coverImage": "assets/works/commercial-adererror-25fw-the-future-is-not-set.jpg",
          "links": {
            "live": "https://www.youtube.com/watch?v=M2le6YMGBmc",
            "case_study": ""
          }
        },
        {
          "id": "commercial-1785174793877",
          "title": "V Magazine - Fall In Line: Today's Top Looks On The Models Of Tomorrow",
          "year": "2025",
          "role": "Colorist",
          "description": "Color graded a promotional video for V Magazine, enhancing its signature high-contrast, editorial aesthetic — translating the magazine's bold, fashion-forward visual identity into motion.",
          "tags": [
            "Fashion",
            "Brand"
          ],
          "coverImage": "assets/works/commercial-v-magazine-fall-in-line-today-s-top-looks-on-the.jpg",
          "links": {
            "live": "https://www.youtube.com/watch?v=mt_eUI-zh1I",
            "case_study": "https://vmagazine.com/article/fall-in-line-todays-top-looks-on-the-models-of-tomorrow/"
          }
        },
        {
          "id": "comm-4",
          "title": "Le Vian Jewelry - Multiple Campaigns",
          "year": "2024-2026",
          "role": "Colorist",
          "description": "Ongoing commercial work for a U.S.-based luxury jewelry brand. Delivered a premium, polished visual aesthetic closely aligned with established brand identity guidelines across multiple campaigns.",
          "tags": [
            "Luxury",
            "Jewelry",
            "Ongoing",
            "Brand"
          ],
          "coverImage": "assets/works/commercial-le-vian-jewelry-multiple-campaigns.jpg",
          "links": {
            "live": "https://www.youtube.com/watch?v=_UVmnvVM2eQ&list=PLNm6V-77bBMDXn9Ksg6adsjWpBPjn-wLN",
            "case_study": ""
          }
        },
        {
          "id": "commercial-1785173520504",
          "title": "Ralliant Split-Second Ejection: A Precision Story from PacSci EMC",
          "year": "2026",
          "role": "Colorist",
          "description": "The Campaign features U.S. Navy pilot Brandon Michaelis recounting a mid-flight collision where PacSci EMC's ejection system got him safely out in 350 milliseconds. It then showcases how PacSci EMC, a Ralliant company, engineered a 3-millisecond emergency egress system for the U.S. Army's new MV-75 helicopters — technology estimated to have saved over 1,500 lives.",
          "tags": [
            "TVC",
            "Brand"
          ],
          "coverImage": "assets/works/commercial-ralliant-split-second-ejection-a-precision-story.jpg",
          "links": {
            "live": "https://www.youtube.com/watch?v=T4744u1P1xQ&t=51s",
            "case_study": "https://ralliant.com/stories/SavingSoldierLiveswithPrecisionEnergeticsSystems?&utm_campaign=2026-q3-ralliant&utm_medium=social&utm_source=youtube&utm_content=organic-video&utm_term=pfwm-launch-june-16"
          }
        },
        {
          "id": "comm-3",
          "title": "Maxi-Cosi - Multiple Campaigns",
          "year": "2024-2025",
          "role": "Colorist",
          "description": "New product launch advertising for Maxi-Cosi. Part of an ongoing client relationship — delivered brand-consistent imaging and color across multiple campaign phases, maintaining visual continuity across all assets.",
          "tags": [
            "TVC",
            "Brand",
            "Ongoing"
          ],
          "coverImage": "assets/works/commercial-maxi-cosi-multiple-campaigns.jpg",
          "links": {
            "live": "https://www.youtube.com/watch?v=nvqyiolFuxE",
            "case_study": ""
          }
        },
        {
          "id": "commercial-1785183336402",
          "title": "Fionn MacCool's - Tradition",
          "year": "2024",
          "role": "Colorist",
          "description": "Served as colorist on Fionn MacCool's – Tradition, a commercial for the pub chain. Crafted a warm, inviting grade to highlight the convivial atmosphere of friends gathering over food and drink.",
          "tags": [
            "Brand",
            "Food"
          ],
          "coverImage": "assets/works/commercial-fionn-maccool-s-tradition.jpg",
          "links": {
            "live": "https://www.youtube.com/watch?v=WijbwJHDCig",
            "case_study": ""
          }
        },
        {
          "id": "commercial-1785225872302",
          "title": "La Belle & La Boeuf - L'Impasse avec Arber Xhekaj",
          "year": "2024",
          "role": "Colorist",
          "description": "Served as colorist on La Belle & La Boeuf – L'Impasse, a commercial for the Montreal burger chain featuring NHL defenceman Arber Xhekaj of the Montreal Canadiens. Crafted a warm, moody grade suited to the restaurant's lively atmosphere.",
          "tags": [
            "Brand",
            "Food"
          ],
          "coverImage": "assets/works/commercial-la-belle-la-boeuf-l-impasse-avec-arber-xhekaj.jpg",
          "links": {
            "live": "https://www.youtube.com/watch?v=XngB4NdcUIw",
            "case_study": ""
          }
        },
        {
          "id": "commercial-1785175270437",
          "title": "GXG New Urban - Lift",
          "year": "2024",
          "role": "Colorist",
          "description": "Color graded a series of e-commerce videos for GXG's New Urban collection, building a clean, contemporary look that reinforces the brand's urban menswear identity.",
          "tags": [
            "E-Commerce",
            "Brand"
          ],
          "coverImage": "assets/works/commercial-gxg-new-urban-lift.jpg",
          "links": {
            "live": "",
            "case_study": ""
          }
        },
        {
          "id": "commercial-1785183783439",
          "title": "COMBO SS19 ",
          "year": "2018",
          "role": "Editor, Colorist",
          "description": "Served as editor and colorist on COMBO SS19, a fashion commercial featuring Chinese supermodel and actor Zhang Liang — the first Chinese model to walk the Milan Fashion Week runway. Crafted a clean, polished grade to complement the brand's contemporary aesthetic.",
          "tags": [
            "Fashion",
            "Brand"
          ],
          "coverImage": "assets/works/commercial-combo-ss19.jpg",
          "links": {
            "live": "",
            "case_study": ""
          }
        },
        {
          "id": "commercial-1785183482102",
          "title": "MENHARDU FW19",
          "year": "2019",
          "role": "Camera Operator, Editor, Colorist",
          "description": "Served as camera operator, editor, and colorist on Menhardum FW19 film, a fashion commercial for the brand's Fall/Winter collection. Delivered a muted, cinematic grade to complement the collection's tailored, understated aesthetic.",
          "tags": [
            "Fashion",
            "Brand"
          ],
          "coverImage": "assets/works/commercial-menhardu-fw19.jpg",
          "links": {
            "live": "",
            "case_study": ""
          }
        },
        {
          "id": "commercial-1785183596672",
          "title": "HOPESHOW SS19",
          "year": "2018",
          "role": "Editor, Colorist",
          "description": "Served as editor and colorist on Hopeshow SS19, a fashion commercial for the brand's Spring/Summer collection. Built a warm, sun-drenched grade to complement the collection's vibrant, outdoor aesthetic.",
          "tags": [
            "Fashion",
            "Brand"
          ],
          "coverImage": "assets/works/commercial-hopeshow-ss19.jpg",
          "links": {
            "live": "",
            "case_study": ""
          }
        },
        {
          "id": "commercial-1785183729002",
          "title": "VILAN SS19",
          "year": "2018",
          "role": "Editor, Colorist",
          "description": "Served as editor and colorist on VILAN SS19, a fashion commercial for the brand's Spring/Summer collection. Developed a delicate, skin-forward grade with soft contrast to draw focus to the model's features and the collection's intimate aesthetic.",
          "tags": [
            "Fashion",
            "Brand"
          ],
          "coverImage": "assets/works/commercial-vilan-ss19.jpg",
          "links": {
            "live": "",
            "case_study": ""
          }
        }
      ]
    }
  ],
  "experience": [
    {
      "id": "exp-1",
      "period": "Jan 2020 — Present",
      "title": "Colorist / Editor",
      "company": "Freelance",
      "description": "Managed complete color pipelines end-to-end — from dailies ingestion through DCP final delivery — for 60+ narrative films, fashion brands, and commercial clients. Executed color grading in DaVinci Resolve and Premiere Pro across Rec.709, Log, and HDR color spaces; maintained image integrity and color consistency across broadcast, social, and web deliverables with full QC sign-off. Built and delivered DCPs for cinema room screenings. Verified metadata, export specifications, and cross-platform compatibility at each delivery stage.",
      "tags": [
        "DaVinci Resolve",
        "DCP Delivery",
        "QC"
      ]
    },
    {
      "id": "exp-2",
      "period": "Jul 2021 — Present",
      "title": "Camera Operator / Assistant",
      "company": "Freelance",
      "description": "Operated ARRI, Sony, Canon, and Blackmagic camera systems on commercial and narrative productions; executed pull focus and supported lighting setups under DP direction. Managed full on-set media workflow: media ingestion, secure offload, file verification, metadata prep, and cross-platform QC; fulfilled DIT responsibilities across multiple production environments.",
      "tags": [
        "Camera Operation",
        "DIT",
        "Focus Pulling"
      ]
    },
    {
      "id": "exp-3",
      "period": "Aug 2025 — Sep 2025",
      "title": "Pre-Production Producer",
      "company": "DW Media",
      "description": "Led complete pre-production for a web short drama: budget planning, shooting schedule, resource allocation, and vendor management for equipment, catering, and post-production handoff. Liaised with director, cinematographer, and production designer to align creative vision with production logistics.",
      "tags": [
        "Producing",
        "Short Drama",
        "Budgeting"
      ]
    },
    {
      "id": "exp-4",
      "period": "Mar 2024 — Sep 2024",
      "title": "Video Editor & Colorist",
      "company": "Black Box Productions",
      "description": "Edited and color-graded YouTube long-form videos and commercial content from raw footage to final delivery; applied professional color grading across broadcast, social, and web formats. Managed multiple concurrent projects in a fast-paced production environment.",
      "tags": [
        "Editing",
        "Color Grading",
        "YouTube"
      ]
    },
    {
      "id": "exp-5",
      "period": "Oct 2018 — May 2019",
      "title": "Camera Operator / Editor / Colorist",
      "company": "Hangzhou Lintas Advertising",
      "description": "Shot and edited promotional content for local brands; built foundational skills in camera operation, editing, and look development working directly with clients.",
      "tags": [
        "Camera",
        "Editing",
        "Advertising",
        "E-Commerce"
      ]
    },
    {
      "id": "exp-6",
      "period": "2019 — 2023",
      "title": "BFA, Film Production",
      "company": "Mel Hoppenheim School of Cinema · Concordia University",
      "description": "Bachelor of Fine Arts in Film Production, with hands-on training across cinematography, editing, directing, and post-production.",
      "tags": []
    }
  ],
  "contact": {
    "email": "colorgradingvw@gmail.com",
    "phone": "+1 514-570-4877",
    "website": "www.victorqixunwu.com",
    "instagram": "victorqixunwu",
    "facebook": "victorqixunwu",
    "location": "Vancouver, BC, Canada",
    "message": "Whether it's a new project, a collaboration, or just a conversation about color — my inbox is always open."
  },
  "footer": {
    "logo": "VW.",
    "copyright": "© 2026 Victor Qixun Wu. All rights reserved."
  },
  "theme": {
    "bg": "#000a02",
    "surface": "#0c0c0c",
    "border": "#373c38",
    "fg": "#fcfaf2",
    "muted": "#e6e3c5",
    "gray": "#bcb09c",
    "accent": "#405c36",
    "accentSoft": "#85916d",
    "earth": "#595045",
    "sand": "#e6e3c5",
    "washiOpacity": 0.8
  }
};

  var data = FILE_DATA;
  try {
    var draft = localStorage.getItem('portfolio_data');
    if (draft) {
      var parsed = JSON.parse(draft);
      if (parsed && parsed.portfolio) data = parsed;
    }
  } catch (e) { /* ignore unreadable draft */ }

  // A draft may still hold base64 blobs — fall back to the published paths
  // so the site never shows a broken image.
  try {
    if (data !== FILE_DATA) {
      var byId = {};
      FILE_DATA.portfolio.forEach(function (c) {
        c.works.forEach(function (w) { byId[w.id] = w.coverImage; });
      });
      (data.portfolio || []).forEach(function (c) {
        (c.works || []).forEach(function (w) {
          if ((w.coverImage || '').indexOf('data:') === 0 && byId[w.id]) w.coverImage = byId[w.id];
        });
      });
      if ((data.about.photo || '').indexOf('data:') === 0) data.about.photo = FILE_DATA.about.photo;
      if ((data.about.cvUrl || '').indexOf('data:') === 0) data.about.cvUrl = FILE_DATA.about.cvUrl;
    }
  } catch (e) { /* best-effort */ }

  window.PORTFOLIO_DATA      = data;
  window.PORTFOLIO_FILE_DATA = FILE_DATA;
  window.PORTFOLIO_DEFAULTS  = FILE_DATA;
})();
